name: xzz
description: Parse XZZ pcb file.
version: 1.0.0
repository: https://github.com/hndrbrm/xzz

environment:
  sdk: ^3.5.4

dependencies:
  dart_des: ^1.0.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
